name = "johan"
license = "MIT"
licenselink = "https://github.com/canhtran/johan/blob/main/LICENSE"
description = "johan is a minimal Hugo blog theme"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/canhtran/johan"

# If you have a running demo of the theme.
demosite = "https://johan.canhtran.me"

tags = ["blog"]
features = ["ultra fast", "github comment", "responsive"]

# If the theme has a single author
[author]
    name = "Tran Duy Canh, Calvin"
    homepage = "https://www.tranduycanh.com"
