name: Publish website

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production


jobs:
  deploy-production:
    name: Deploy to Production
    if: ${{ github.event.inputs.environment == 'production' }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      BUCKET_NAME: ${{ vars.PROD_S3_BUCKET_NAME }}
    steps:
      - name: Install Hugo
        run: sudo apt install -y hugo
      - name: Install aws cli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ""
          workdir: ""
      - name: Set AWS credentials
        run: export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} && export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build
        run: bash imageSync.sh && hugo && cp -f ./assets/favicon.ico ./public/assets/favicon.ico
      - name: Upload files to S3
        run: aws s3 sync public/ s3://${{ env.BUCKET_NAME }}/ --exact-timestamps --delete